//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BorrowBook
    {
        [Key]
        public int BorrowBook_Id { get; set; }
        public string Student_Name { get; set; }
        public string Book_Name { get; set; }
        public string Transaction_Date { get; set; }
        public Nullable<int> Book_Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
    
        public virtual books books { get; set; }
        public virtual Student Student { get; set; }
    }
}
