//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GHOSHEntities : DbContext
    {
        public GHOSHEntities()
            : base("name=GHOSHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Librarian> Librarian { get; set; }
        public virtual DbSet<BorrowBook> BorrowBook { get; set; }
    }
}
