//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.BorrowBook = new HashSet<BorrowBook>();
        }
        [Key]
    
        public int Student_Id { get; set; }

        [Display(Name = "UserName")]
        public string User_Name { get; set; }



        [Display(Name = "Student Name")]
        [Required(ErrorMessage = "Please enter Valid Student Name")]
        public string Student_Name { get; set; }



        [Display(Name = "Email Id")]
        [Required(ErrorMessage = "Please enter Valid Email Id")]
        [MaxLength(50)]
        [DataType(DataType.EmailAddress)]
        public string Email_Id { get; set; }


        [Required(ErrorMessage = "Please select Gender")]
        public string Gender { get; set; }


        [Required(ErrorMessage = "Please select Course")]
        public string Course { get; set; }



        [Required(ErrorMessage = "Please select Semester")]
        public string Semester { get; set; }



        [DataType(DataType.Password)]
        //[RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,15}$", ErrorMessage = "Password must be between 6 and 20 characters and contain one uppercase letter, one lowercase letter, one digit and one special character.")]

        public string Password { get; set; }


        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "The password and RetypePassword does not match")]
        public string RetypePassword { get; set; } //added

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowBook> BorrowBook { get; set; }
    }
}
